FROM node:20-alpine

WORKDIR /frontend
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

# Install dependencies based on the preferred package manager
COPY ./frontend/package*.json .
RUN npm install

COPY ./frontend .

CMD ["npm", "run", "dev"]