FROM python:3.11.3-bullseye

# Install server side
COPY backend/src /backend/
WORKDIR "/backend"
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]