FROM python:3.11.3-bullseye

# Install client sdk
COPY loopquest /sdk/loopquest/
COPY requirements.txt /sdk/requirements.txt
COPY setup.py /sdk/setup.py
COPY README.md /sdk/README.md
WORKDIR "/sdk"
RUN pip install -e .

# Install server side
COPY backend/src /backend/

WORKDIR "/backend"

RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]