FROM python:3.11.3-bullseye

# Install server side
COPY backend/src /backend/
WORKDIR "/backend"
RUN pip install -r requirements.txt
RUN pip install "gymnasium-robotics[mujoco-py]"
RUN pip install "gymnasium[box2d]"

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]