export default function Instruction() {
  return (
    <div className="hero min-h-screen bg-base-100">
      <div className="hero-content text-center">
        <div className="max-w-xl">
          <h1 className="text-3xl font-bold">QuickStart Guide</h1>
          <p className="py-6">
            Welcome to the Open-sourced Loopquest Cloud 🎉!
          </p>
          <div className="card text-left">
            <div className="card-body">
              <h2 className="card-title">Install</h2>
              <div className="mockup-code">
                <pre>
                  <code>pip install loopquest</code>
                </pre>
              </div>
            </div>
          </div>

          <div className="card text-left">
            <div className="card-body">
              <h2 className="card-title">How to use</h2>
              <p>
                Add 2 extra lines of code. 🔓 Unlock the whole LoopQuest
                experience.
              </p>
              <div className="mockup-code">
                <pre>
                  <code>import gymnasium</code>
                </pre>
                <pre>
                  <code className="text-orange-300">import loopquest</code>
                </pre>
                <pre>
                  <code className="text-orange-300">
                    env = loopquest.make_env(
                  </code>
                </pre>
                <pre>
                  <code>
                    {"  "}gymnasium.make(&quot;MountainCarContinuous-v0&quot;,
                  </code>
                </pre>
                <pre>
                  <code>
                    {"                 "}render_mode=&quot;rgb_array&quot;)
                  </code>
                </pre>

                <pre>
                  <code className="text-orange-300">)</code>
                </pre>
                <pre>
                  <code>obs, info = env.reset()</code>
                </pre>
                <pre>
                  <code>for i in range(100):</code>
                </pre>
                <pre>
                  <code>{"  "}action = env.action_space.sample()</code>
                </pre>
                <pre>
                  <code>{"  "}obs, reward, terminated, truncated, info =</code>
                </pre>
                <pre>
                  <code>{"  "}env.step(action)</code>
                </pre>
                <pre>
                  <code>{"  "}rgb_array = env.render()</code>
                </pre>
                <pre>
                  <code>{"  "}if terminated or truncated:</code>
                </pre>
                <pre>
                  <code>{"    "}break</code>
                </pre>
                <pre>
                  <code>env.close()</code>
                </pre>
              </div>
              <p>
                Then download the data generated by the experiment for
                foundation model training or offline Reinforcement Learning.
              </p>
              <div className="mockup-code">
                <pre>
                  <code>from loopquest.datasets import load_datasets</code>
                </pre>
                <pre>
                  <code>
                    ds = load_datasets([&quot;exp1&quot;, &quot;exp2&quot;])
                  </code>
                </pre>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
